

on skript start:
	set {battlebox.inprogress} to false

function bbopencages():
	execute console command "/fill 15 60 -302 15 58 -308 air"
	execute console command "/fill 47 60 -308 47 58 -302 air"

function bbclosecages():
	execute console command "/fill 15 60 -302 15 58 -308 lime_stained_glass"
	execute console command "/fill 47 60 -308 47 58 -302 black_stained_glass"

function bbgivekit(p:player):
	loop 7 times:
		give slot ({mcc.bb.selectedkit.%{_p}'s name%}*9 + loop-number + 1) of {mcc.bb.lobbykitselect} to {_p}
	if {battlebox.team.%{_p}%} is equal to "dream":
		givewool({_p}, 4)
		setboots({_p}, 4)
	else:
		givewool({_p}, 12)
		setboots({_p}, 12)
	 
function bballready() :: boolean:
	set {_good1} to false
	set {_good2} to false
	loop all players:
		if {battlebox.playing.%loop-player%} is true:
			if {battlebox.ready.%loop-player%} is false:
				return false
			else:
				if {battlebox.team.%loop-player%} is equal to "dream":
					set {_good1} to true
				else:
					set {_good2} to true
	if {_good1} is false:
		return false
	if {_good2} is false:
		return false
	return true

function bbstartgame():
	loop all players:
		if {battlebox.playing.%loop-player%} is true:
			clear the loop-player's inventory
			bbgivekit(loop-player)
			set loop-player's health to 10
			set loop-player's hunger to 10
			set loop-player's game mode to survival
			clear the loop-player's fastboard
			set title of loop-player's fastboard to "<light blue>Battle Box"
			set line 14 of loop-player's fastboard to ""
			set line 13 of loop-player's fastboard to "<lime>Get ready!"	
			# if {battlebox.team.%loop-player%} is equal to "dream":
			# 	teleport loop-player to location at 11, 51, -304 of world "world" 
			# else:
			# 	teleport loop-player to location at 51, 51, -304 of world "world" 
	bbclosecages()
	loop all players:
		if {battlebox.playing.%loop-player%} is true:
			execute console command "/note 6 %loop-player%"
			send title "<light blue> Starting in" with subtitle "<red>3" to the loop-player for 1 second
	wait 1 second
	loop all players:
		if {battlebox.playing.%loop-player%} is true:
			execute console command "/note 6 %loop-player%"
			send title "<light blue> Starting in" with subtitle "<yellow>2" to the loop-player for 1 second
	wait 1 second
	loop all players:
		if {battlebox.playing.%loop-player%} is true:
			execute console command "/note 6 %loop-player%"
			send title "<light blue> Starting in" with subtitle "<green>1" to the loop-player for 1 second
	wait 1 second
	loop all players:
		if {battlebox.playing.%loop-player%} is true:
			execute console command "/note 18 %loop-player%"
	drop a splash potion of healing at {bbpot1} without velocity
	drop a splash potion of healing at {bbpot2} without velocity 
	set {battlebox.timeleft} to 75
	teamglowlobbybb(true)
	bbopencages()
	set {battlebox.inprogress} to true




function bbgameover() :: number:
	set {_green} to 0
	set {_black} to 0
	loop blocks in radius 2.5 of {bbwoolloc}:
		if loop-block is black wool:
			add 1 to {_black}
		else if loop-block is lime wool:
			add 1 to {_green}
	if {_black} is equal to 9:
		return 1 
	if {_green} is equal to 9:
		return 2 
	return 0 

command /setbbstuff:
	trigger:
		if {mmcc.hosts::*} contains command sender:
			set {bbwoolloc} to the location 31, 101, -305 in world "world"

function bbendgame(n: number):
	if {_n} is equal to -1:
		broadcast "<light blue>[Battle Box] <yellow>Battle Box ended in a tie because everyone died."
	if {_n} is equal to 0:
		broadcast "<light blue>[Battle Box] <yellow>Battle Box ended in a tie because time ran out."
	else if {_n} is equal to 2:
		broadcast "<light blue>[Battle Box] <lime>Green Dreams<yellow> have won Battle Box!"	
	else if {_n} is equal to 1:
		broadcast "<light blue>[Battle Box] <gray>Black BadBoyHalos<yellow> have won Battle Box!"	
	set {battlebox.inprogress} to false
	wait 3 seconds
	loop all dropped items in "world":
		if x-coordinate of loop-entity is between 59 and 3:
			if y-coordinate of loop-entity is between 88 and 43:
				if z-coordinate of loop-entity is between -329 and -278:
					delete the loop-entity
	loop blocks in radius 2.5 of {bbwoolloc}:
		if block below loop-block is bedrock:
			set loop-block to white wool
	loop all players:
		if {battlebox.playing.%loop-player%} is true:
			teleport loop-player to {bbwaitingloc}
			clear the loop-player's fastboard
			set the loop-player's game mode to adventure
		set {battlebox.playing.%loop-player%} to false
		set {battlebox.ready.%loop-player%} to false
		set {battlebox.team.%loop-player%} to "none"
		set {battlebox.kit.%loop-player%} to 0
	loop {lobby.bb.cobwebs::*}:
		set block at loop-value's location to air
	delete {lobby.bb.cobwebs::*}
	set {battlebox.timeleft} to 0	
	resetlobbybbkits()
	bbclosecages()
	teamglowlobbybb(false)
	execute console command "/schempaste lobbybbreset world 31 57 -305"

function resetlobbybbkits():
	loop 2 times:
		set {_temp} to chest inventory with 5 rows
		loop 45 times:
			set slot loop-number-2 of {_temp} to slot loop-number-2 of {mcc.bb.lobbykitselect}
		set {mcc.bb.kitselect.lobby%loop-number-1%} to {_temp}
		delete {_temp}

on rightclick:
	player's world is "world"
	{battlebox.playing.%player%} is true
	if name of player's tool is "<light cyan>Ability: Syphon Heal":
	#broadcast player's target
		if player's target is a player:
			#broadcast {mcc.team.%player's target's name%}
			if {mcc.team.%player's target's name%} is equal to {mcc.team.%player%}:
				#broadcast {mcc.battlebox.abilitycooldown.%player%}
				if {mcc.battlebox.abilitycooldown.%player%} is less than 1:
					damage player by 2 hearts
					heal player's target by 3 hearts
					set {mcc.battlebox.abilitycooldown.%player%} to 2
	if player's tool is end crystal:
		if {mcc.battlebox.abilitycooldown.%player%} is less than 1:
			#broadcast ((player's health)^(1/3))
			set {_exp} to (1*(player's health)^(1/3))
			add potion effect of resistance of tier 255 for 0.1 seconds to potion effects of player 
			spawn creeper at player's location:
				
				set explosive yield of spawned entity to {_exp}
				add "att %player%" to the scoreboard tags of the spawned entity
				instantly explode spawned entity
			#create safe explosion of force (player's health^(1/3)) at player's location
			set {mcc.battlebox.abilitycooldown.%player%} to 20
	if player's tool is obsidian:
		if {mcc.battlebox.abilitycooldown.%player%} is less than 1:
			set {mcc.battlebox.parrying.%player%} to true
			set glowing of player to true
			set {mcc.battlebox.abilitycooldown.%player%} to 3
			wait 0.5 seconds
			if {mcc.battlebox.parrying.%player%} is true:
				set {mcc.battlebox.parrying.%player%} to false
				set glowing of player to false
				# apply slowness of tier 2 to player for 2 seconds
				message "You did not parry an attack!" to event-player
	if player's tool is feather:
		if {mcc.battlebox.abilitycooldown.%player%} is less than 1:
			set {mcc.battlebox.abilitycooldown.%player%} to 5
			push player forward at speed 1
	if player's tool is brick:
		set {_helm} to player's helmet
		set player's helmet to brick block
		wait 5 seconds
		set player's helmet to {_helm}
	
on damage:
	if {mcc.battlebox.parrying.%victim%} is true:
		cancel event
		set {_v} to vector between victim and the location 2 block above attacker's location
		broadcast {_v}
		push attacker {_v} at speed 2
		set {mcc.battlebox.parrying.%victim%} to false
		set glowing of victim to false
		message "Your attack was parried!" to attacker
		message "Successfully parried an attack!" to victim

every second:
	loop all players in world "world":
		if {battlebox.playing.%loop-player%} is true:
			if {mcc.battlebox.abilitycooldown.%loop-player%} isn't set:
				set {mcc.battlebox.abilitycooldown.%loop-player%} to 0
			if {mcc.battlebox.abilitycooldown.%loop-player%} is more than 0:
				subtract 1 from {mcc.battlebox.abilitycooldown.%loop-player%}
				send action bar "Ability Cooldown: <light cyan>%{mcc.battlebox.abilitycooldown.%loop-player%}%<reset> Seconds" to loop-player

# on rightclick:
# 	event-block is tagged as tag "buttons"
# 	if {battlebox.playing.%player%} is true:
# 		if x-coordinate of event-location is equal to 6.5:
# 			bbkit(player, 1)		
# 		if x-coordinate of event-location is equal to 8.5:
# 			bbkit(player, 2)		
# 		if x-coordinate of event-location is equal to 10.5:
# 			bbkit(player, 3)		
# 		if x-coordinate of event-location is equal to 12.5:
# 			bbkit(player, 4)		
# 		if x-coordinate of event-location is equal to 56.5:
# 			bbkit(player, 1)		
# 		if x-coordinate of event-location is equal to 54.5:
# 			bbkit(player, 2)		
# 		if x-coordinate of event-location is equal to 52.5:
# 			bbkit(player, 3)		
# 		if x-coordinate of event-location is equal to 50.5:
# 			bbkit(player, 4)		

command /openbattleboxlobbykitselect:
	permission: op
	trigger:
		if {mcc.bb.lobbykitselect} isn't set:
			set {mcc.bb.lobbykitselect} to chest inventory with 5 rows
		open {mcc.bb.lobbykitselect} to player
		loop 45 times:
			set slot loop-number of {mcc.bb.lobbykitselect} to {mcc.bb.lobbykitselectstorage::%loop-number%}

on inventory close:
	if event-inventory is {mcc.bb.lobbykitselect}:
		loop 45 times:
			set {mcc.bb.lobbykitselectstorage::%loop-number%} to slot loop-number of {mcc.bb.lobbykitselect}

on rightclick:
	player's world is "world"
	player's tool is recovery compass
	if {battlebox.playing.%player%} is true:
		if {battlebox.team.%player%} is equal to "dream":
			open {mcc.bb.kitselect.lobby1} to player
		else:
			open {mcc.bb.kitselect.lobby2} to player

on inventory click:
	player's world is "world"
	if {battlebox.team.%player%} is "dream":
		if player's current inventory is {mcc.bb.kitselect.lobby1}:
			cancel event
			if slot floor(index of event-slot/9)*9 of {mcc.bb.kitselect.lobby1} isn't player head:
				if {mcc.bb.selectedkit.%player's name%} is set:
					set slot {mcc.bb.selectedkit.%player's name%}*9 of {mcc.bb.kitselect.lobby1} to air
				set {mcc.bb.selectedkit.%player's name%} to floor(index of event-slot/9)
				set slot {mcc.bb.selectedkit.%player's name%}*9 of {mcc.bb.kitselect.lobby1} to player's skull
			else:
				message "<red>This kit is already taken, please choose another kit."
	else:
		if player's current inventory is {mcc.bb.kitselect.lobby2}:
			cancel event
			if slot floor(index of event-slot/9)*9 of {mcc.bb.kitselect.lobby2} isn't player head:
				if {mcc.bb.selectedkit.%player's name%} is set:
					set slot {mcc.bb.selectedkit.%player's name%}*9 of {mcc.bb.kitselect.lobby2} to air
				set {mcc.bb.selectedkit.%player's name%} to floor(index of event-slot/9)
				set slot {mcc.bb.selectedkit.%player's name%}*9 of {mcc.bb.kitselect.lobby2} to player's skull
			else:
				message "<red>This kit is already taken, please choose another kit."
	

on rightclick:
	event-block is tagged as tag "buttons"
	event-block's z-coord is -231.5
	if "%player's world%" is "world":
		if event-block is in region "minigames":
			if {mcc.currentevent} is not "none":
				message "<pink>You cannot do this now!" to event-player
				exit trigger
			
			if {battlebox.playing.%player%} is false:
				if {battlebox.inprogress} is false:
					broadcast "<light blue>[Battle Box] <white>%player% has joined team <gray>Black BadBoyHalos!"
					teleport player to {bb.lobby.blackspawn}
					clear the player's inventory
					set slot 4 of player's inventory to gunpowder named "<lime>Ready"
					set slot 8 of player's inventory to red dye named "<pink>Leave"
					set {battlebox.team.%player%} to "bad"
					set {battlebox.playing.%player%} to true
					delete {mcc.bb.selectedkit.%player%}
					set {mcc.battlebox.abilitycooldown.%player%} to 0
					give player recovery compass named "<purple>Kit Selection"
				else:
					message "<light blue>[Battle Box] <pink>This arena is in use!" to event-player
			else:
				message "<light blue>[Battle Box] <pink>You are already in this game!" to event-player


on rightclick:
	event-block is tagged as tag "buttons"
	event-block's z-coord is -232.5
	if "%player's world%" is equal to "world":
		if event-block is in region "minigames":
			if {mcc.currentevent} is not equal to "none":
				message "<pink>You cannot do this now!" to event-player
				exit trigger
			if {battlebox.playing.%player%} is false:
				if {battlebox.inprogress} is false:
					broadcast "<light blue>[Battle Box] <white>%player% has joined team <lime>Green Dreams!"
					teleport player to {bb.lobby.greenspawn}
					clear the player's inventory
					set slot 4 of player's inventory to gunpowder named "<lime>Ready"
					set slot 8 of player's inventory to red dye named "<pink>Leave"
					set {battlebox.team.%player%} to "dream"
					set {battlebox.playing.%player%} to true
					set {mcc.battlebox.abilitycooldown.%player%} to 0
					delete {mcc.bb.selectedkit.%player%}
					give player recovery compass named "<purple>Kit Selection"
				else:
					message "<light blue>[Battle Box] <pink>This arena is in use!" to event-player
			else:
				message "<light blue>[Battle Box] <pink>You are already in this game!" to event-player

on rightclick:
	if {battlebox.playing.%player%} is true:
		if player's tool is red dye named "<pink>Leave":
			set {battlebox.playing.%player%} to false
			set {battlebox.ready.%player%} to false
			set {battlebox.team.%player%} to "none"
			set {battlebox.kit.%player%} to 0
			set player's game mode to adventure
			teleport player to {bbdeadspawn}
		else if player's tool is gunpowder named "<lime>Ready":
			set {battlebox.ready.%player%} to true
			if bballready() is true:
				bbstartgame()
			else:
				set player's tool to lime dye named "<gray>Unready"
		else if player's tool is lime dye named "<gray>Unready":
			set {battlebox.ready.%player%} to false 
			set player's tool to gunpowder named "<lime>Ready"
	

on join:
	if {battlebox.playing.%player%} is true:
		set {battlebox.playing.%player%} to false
		set {battlebox.ready.%player%} to false
		set {battlebox.team.%player%} to "none"
		set {battlebox.kit.%player%} to 0
		set player's game mode to adventure
		teleport player to {bbdeadspawn}

on damage:
	victim is a player
	damage is greater than or equal to victim's health
	if {battlebox.playing.%victim%} is true: 
		if attacker is a player:
			if {battlebox.team.%victim%} is equal to "dream":
				broadcast "<light blue>[Battle Box] <lime>%victim%<yellow> was killed by <gray>%attacker%"
			else:
				broadcast "<light blue>[Battle Box] <gray>%victim%<yellow> was killed by <lime>%attacker%"
		else if attacker is TNT:
			loop all players:
				if attacker has scoreboard tags "att %loop-player's name%":
					set {_atkr} to loop-player
			if {battlebox.team.%victim%} is equal to "dream":
				broadcast "<light blue>[Battle Box] <lime>%victim%<yellow> was exploded by <gray>%{_atkr}%"
			else:
				broadcast "<light blue>[Battle Box] <gray>%victim%<yellow> was exploded by <lime>%{_atkr}%"
		set {battlebox.playing.%victim%} to false
		set {battlebox.ready.%victim%} to false
		set {battlebox.team.%victim%} to "none"
		set {battlebox.kit.%victim%} to 0
		teleport victim to {bbdeadspawn}
		set the victim's game mode to adventure
		send "<light blue>[Battle Box] <pink>You died!" to the victim		
		clear the victim's fastboard
		set victim's health to 10
		cancel event

	

on damage:
	victim is a player
	attacker is a player
	if {battlebox.playing.%attacker%} is true:
		if {battlebox.playing.%victim%} is true:
			if {battlebox.team.%victim%} is equal to {battlebox.team.%attacker%}:
				if attacker is not equal to victim:
					send "<pink>You cannot attack teammates!" to attacker
					cancel event



on break:
	if {battlebox.playing.%player%} is true:
		if block is not wool or cobweb:
			cancel event

on place:
	if {battlebox.playing.%player%} is true:
		if block is not wool or cobweb or tnt:
			cancel event
		if block is cobweb or tnt:
			loop blocks in radius 1 of event-block:
				if loop-block is bubble column:
					set {_bad} to true
			if {_bad} is true:
				cancel event
				if event-block is tnt:
					remove 1 tnt from player
		if block is tnt:
			wait a tick
			set event-block to air
			spawn a primed tnt at event-location
			add "att %player%" to the scoreboard tags of the spawned primed tnt
		if block is wool:
			set {bb.good} to false
			if x-coordinate of event-location is between 30.5 and 32.5:
				if y-coordinate of event-location is equal to 56.5:
					if z-coordinate of event-location is between -303.5 and -305.5:
						set {bb.good} to true			
			if {bb.good} is false:
				cancel event
			else:
				if bbgameover() is greater than 0:
					bbendgame(bbgameover())	
		else if block is cobweb:
			add block to {lobby.bb.cobwebs::*}

on explode:
	world is "world"
	clear exploded blocks

on hunger meter change:
	if {battlebox.playing.%player%} is true:
		cancel event


every second in "world":
	if {battlebox.inprogress} is true:
		set {_dream} to 0
		set {_bad} to 0
		if {battlebox.timeleft} is greater than 0:
			subtract 1 from {battlebox.timeleft}
		else:
			bbendgame(0)
			stop
		loop all players:
			if {battlebox.playing.%loop-player%} is true:
				if {battlebox.team.%loop-player%} is equal to "dream":
					add 1 to {_dream}
				else:
					add 1 to {_bad}
		if {_dream} is equal to 0:
			if {_bad} is equal to 0:
				bbendgame(-1)
		loop all players:
			if {battlebox.playing.%loop-player%} is true:
				set line 13 of loop-player's fastboard to "<pink>Time left: <white>%time({battlebox.timeleft})%"	
				set line 12 of loop-player's fastboard to ""
				set line 11 of loop-player's fastboard to "<lime>Green Dreams: %{_dream}%"
				set line 10 of loop-player's fastboard to "<gray>Black BadBoyHalos: %{_bad}%"


